apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  labels:
    app: flag-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: acrtogglemasterprod.azurecr.io/flag-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: flags-database-url
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.togglemaster-auth.svc.cluster.local:8001"
            - name: OTEL_SERVICE_NAME
              value: "flag-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=prod"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15
