apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: togglemaster-flags
type: Opaque
stringData:
  flags-database-url: "postgres://pgadmin:P%40ssw0rd2026%21Secure@pg-flags-togglemaster-prod.postgres.database.azure.com:5432/flags_db?sslmode=require"
