apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: togglemaster-targeting
type: Opaque
stringData:
  targeting-database-url: "postgres://pgadmin:P%40ssw0rd2026%21Secure@pg-targeting-togglemaster-prod.postgres.database.azure.com:5432/targeting_db?sslmode=require"
