apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: togglemaster-analytics
data:
  cloud-provider: "azure"
  servicebus-queue-name: "evaluation-events"
  cosmosdb-table-name: "EvaluationEvents"
