apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster-analytics

resources:
  - ../../base
  - configmap.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: acrtogglemasterprod.azurecr.io/analytics-service
    newTag: 263e05687c8c329a1105757ca30759ca727f97e0
