apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: togglemaster-analytics
resources:
- ../../base
- configmap.yaml
- hpa.yaml
- ingress.yaml
- secrets.yaml
images:
- name: acrtogglemasterprod.azurecr.io/analytics-service
  newTag: dff6caf0f02344e21861ceca624fd71dd4a73316
