apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: togglemaster-analytics
resources:
- ../../base
- configmap.yaml
- hpa.yaml
- ingress.yaml
- secrets.yaml
images:
- name: acrtogglemasterprod.azurecr.io/analytics-service
  newTag: 09c0c3d75ae7c2fd955a532f5252842c8f558ab0
