apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: togglemaster-analytics
type: Opaque
stringData:
  servicebus-connection-string: "Endpoint=sb://sb-togglemaster-prod.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=A0IfZy9gWI7Pu3vJZIdn4N7Zq1LFqkpX7+ASbG/IRPg="
  cosmosdb-connection-string: "DefaultEndpointsProtocol=https;AccountName=cosmos-togglemaster-prod;AccountKey=s6ZH0TvZRx6hP37aRcuKhtU4AtdvCzyZvCYiSMW60o8Syppp8o8u13oplayWK3cDIdAskTuoRPenACDb6dzxKA==;TableEndpoint=https://cosmos-togglemaster-prod.table.cosmos.azure.com:443/;"
