apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: togglemaster-analytics
type: Opaque
stringData:
  servicebus-connection-string: "Endpoint=sb://sb-togglemaster-prod.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=D8T1Rtvw/SFiZY0am0h4W6AsY58hCs746+ASbMthSD8="
  cosmosdb-connection-string: "DefaultEndpointsProtocol=https;AccountName=cosmos-togglemaster-prod;AccountKey=ntYdGs6ffMn7eaIJcGA7yuz1dyWlMJ9ef4iLhCxboKfEZyUN83xcUjc32M1TDtTyFxnTSSr5fpEGACDb4KjRNA==;TableEndpoint=https://cosmos-togglemaster-prod.table.cosmos.azure.com:443/;"
