apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-auth
  namespace: togglemaster-auth
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS api_keys (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        key_hash VARCHAR(64) NOT NULL UNIQUE,
        is_active BOOLEAN DEFAULT true,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO api_keys (name, key_hash) VALUES
    ('internal-service-key', '89fdbf4f02459989b93fb00449bd55d7b066727a94743b40e2d94c06b80175bb')
    ON CONFLICT (key_hash) DO NOTHING;
