apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: togglemaster-auth
type: Opaque
stringData:
  auth-database-url: "postgres://pgadmin:P%40ssw0rd2026%21Secure@pg-auth-togglemaster-prod.postgres.database.azure.com:5432/auth_db?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster-auth
type: Opaque
stringData:
  master-key: "master-key-prod-2026"
