apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-auth
  labels:
    app.kubernetes.io/part-of: togglemaster
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-flags
  labels:
    app.kubernetes.io/part-of: togglemaster
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-targeting
  labels:
    app.kubernetes.io/part-of: togglemaster
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-evaluation
  labels:
    app.kubernetes.io/part-of: togglemaster
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-analytics
  labels:
    app.kubernetes.io/part-of: togglemaster
