apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster-evaluation

resources:
  - ../../base
  - configmap.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: acrtogglemasterprod.azurecr.io/evaluation-service
    newTag: latest
