apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: togglemaster-evaluation
type: Opaque
stringData:
  redis-url: "redis://:Rsq5npTXBLQL2VbUFbINEh1JxmcOc5S92AzCaKtLCjk=@redis-togglemaster-prod.redis.cache.windows.net:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: togglemaster-evaluation
type: Opaque
stringData:
  servicebus-connection-string: "Endpoint=sb://sb-togglemaster-prod.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=D8T1Rtvw/SFiZY0am0h4W6AsY58hCs746+ASbMthSD8="
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster-evaluation
type: Opaque
stringData:
  service-api-key: "tm_key_service_internal_dev"
